### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by maximusblade** [DraperStudio/Laravel-Voteable#1]
Nice to have:

- List all voted models
- List voted models filtered by *
- Remove All votes  from Model
- Get models votes filtered by * (date 
- Get models votes filtered by 
- -most upvotes within timespan
- -most downvotes within timespan

 most upvotes within timespan

- list

**Comment by DraperStudio** [comment]
The `votes` method returns a `morphMany` relationship so you can just call any Elouquent methods on those. Also there is already a `countByDate` method which you could slightly modifiy for your use.

Might add helper methods one day, but not for now.
